### PR TITLE
Depracated ioutil

### PR DESCRIPTION
**Pull request by matthew-robinson-ons**
# What and why?
Update deprecated package import to recommended method 

# How to test?

Run acceptance tests to ensure a collection exercise goes live.

# Trello
https://trello.com/c/2KA3f1V6/2187-update-deprecated-ioutilreadall-function-call-in-ras-rm-csv-worker

### CODE REVIEW

**Comment by matthew-robinson-ons** [comment]
[Update deprecated ioutil.ReadAll function call in ras-rm-csv-worker](https://trello.com/c/2KA3f1V6/2187-update-deprecated-ioutilreadall-function-call-in-ras-rm-csv-worker)

**Review by anwilkie — APPROVED** [review]
Deployed this PR and ran acceptance tests successfully.

**Pull request merged**
